---
# Source: umbrella/charts/core/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: notes-client-demo
  labels:
    app: notes-client-demo
    version: dev
    chart: notes-client-demo
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 5000
      protocol: TCP
  selector:
    app: notes-client-demo
