apiVersion: v1
kind: PersistentVolume
metadata:
  name: notes-server-demo-db
spec:
  storageClassName: ""
  capacity:
    storage: 100G
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: notes-server-demo-db
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: notes-server-demo-db
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100G
